name: Debug Build and Test

on: [push, pull_request]

jobs:
  build-debug:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['2.0']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore --verbosity normal
      - name: Build Debug
        run: dotnet build --no-restore --verbosity normal --configuration Debug
      - name: Test Debug
        run: dotnet test --no-build --verbosity normal --configuration Debug